Update gh-pages.yml (#678)
* Update gh-pages.yml

* up

diff --git a/.github/workflows/gh-pages.yml b/.github/workflows/gh-pages.yml
--- a/.github/workflows/gh-pages.yml
+++ b/.github/workflows/gh-pages.yml
@@ -31,15 +31,24 @@ jobs:
           BASE_BRANCH: develop
           BRANCH: master
           FOLDER: dist
-#           CLEAN: true
-
-      - run: |
-          echo "deployment_status is"
-          echo $deployment_status
-          echo "${{env.DEPLOYMENT_STATUS}}"
+      #           CLEAN: true
 
       - name: Run E2E tests
         if: env.DEPLOYMENT_STATUS == 'success'
         run: |
-          sleep 10
-          npm test
+          max_attempts=30
+          attempt=0
+          while [ $attempt -lt $max_attempts ]; do
+            if npm test | grep -q "Expected Content"; then
+              echo "Tests passed"
+              break
+            fi
+
+            attempt=$((attempt+1))
+            sleep 10
+          done
+
+          if [ $attempt -eq $max_attempts ]; then
+            echo "Tests failed"
+            exit 1
+          fi
